### ISSUE TITLE
Why check for existence of key when the database already has foreign key constraints

### ISSUE THREAD

**Issue by sacheendra** [atlarge-research/opendc-web-server#2]
In the experiments endpoint, it is checked whether the simulation id already exists before creating an experiment with that simulation id. What is the need for this when the database already has foreign key constraints?

location: https://github.com/tudelft-atlarge/opendc-web-server/blob/master/opendc/api/v1/simulations/simulationId/experiments/endpoint.py#L81

@leonoverweel

**Comment by leonoverweel** [comment]
It's easier to throw the right error code this way, because the foreign key exceptions thrown by SQLite are a bit weird to catch.

**Comment by sacheendra** [comment]
ok. Maybe we could change that sometime in the future, when we move to a db with better errors. :-)

**Comment by leonoverweel** [comment]
Yes. The web server can probably be abstracted a bit more too - I have a couple of ideas. Closing this issue for now; we'll reopen when we switch away from SQLite.
